version: '3.7'

x-buildargs: &buildargs
    API_BASE_URL: ${API_BASE_URL}
    APP_NAME: ${APP_NAME}
    PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
    SELLER_PANEL_LOGIN_URL: ${SELLER_PANEL_LOGIN_URL}
    NEED_AUTH: ${NEED_AUTH}
    ACADEMY_VERSION: ${ACADEMY_VERSION}
    PUSHER_KEY: ${PUSHER_KEY}
    PUSHER_WSHOST: ${PUSHER_WSHOST}
    PUSHER_WSPORT: ${PUSHER_WSPORT}
    PUSHER_FORCETLS: ${PUSHER_FORCETLS}

x-module: &module
    env_file: .env
    build:
        context: .
        args:
            API_BASE_URL: ${API_BASE_URL}
            APP_NAME: ${APP_NAME}
            PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
            SELLER_PANEL_LOGIN_URL: ${SELLER_PANEL_LOGIN_URL}
            NEED_AUTH: ${NEED_AUTH}
            ACADEMY_VERSION: ${ACADEMY_VERSION}
            PUSHER_KEY: ${PUSHER_KEY}
            PUSHER_WSHOST: ${PUSHER_WSHOST}
            PUSHER_WSPORT: ${PUSHER_WSPORT}
            PUSHER_FORCETLS: ${PUSHER_FORCETLS}
    restart: unless-stopped
    depends_on:
        - core

services:
    core:
        image: seller-refactored-ui-core:latest
        env_file: .env
        platform: linux/x86_64
        build:
            context: .
            args:
                <<: *buildargs
        container_name: refactored-seller-core-ui-core
        restart: unless-stopped
    


    nginx:
        image: nginx:latest
        container_name: refactored-seller-academy-ui-rproxy
        ports:
            - 3450:80
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - core
