version: '3.7'

x-buildargs: &buildargs
    API_BASE_URL: ${API_BASE_URL}
    APP_NAME: ${APP_NAME}
    PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
    SELLER_PANEL_LOGIN_URL: ${SELLER_PANEL_LOGIN_URL}
    NEED_AUTH: ${NEED_AUTH}
    ACADEMY_VERSION: ${ACADEMY_VERSION}

x-module: &module
    env_file: .env
    build:
        context: .
        args:
            API_BASE_URL: ${API_BASE_URL}
            APP_NAME: ${APP_NAME}
            PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
            SELLER_PANEL_LOGIN_URL: ${SELLER_PANEL_LOGIN_URL}
            NEED_AUTH: ${NEED_AUTH}
            ACADEMY_VERSION: ${ACADEMY_VERSION}
    restart: unless-stopped
    depends_on:
        - core

services:
    core:
        image: seller-core-ui-core:latest
        env_file: .env
        platform: linux/x86_64
        build:
            context: .
            args:
                <<: *buildargs
                MODULE: core
        container_name: refactored-seller-core-ui-core
        restart: unless-stopped

    academy:
        <<: *module
        image: seller-academy-ui-academy:latest
        platform: linux/x86_64
        build:
            context: .
            args:
                <<: *buildargs
                MODULE: academy
        container_name: refactored-seller-academy-ui-academy
    
    blog:
        <<: *module
        image: seller-academy-ui-blog:latest
        platform: linux/x86_64
        build:
            context: .
            args:
                <<: *buildargs
                MODULE: blog
        container_name: refactored-seller-academy-ui-blog

    forum:
        <<: *module
        image: seller-academy-ui-forum:latest
        platform: linux/x86_64
        build:
            context: .
            args:
                <<: *buildargs
                MODULE: forum
        container_name: refactored-seller-academy-ui-forum

    # panel:
    #     <<: *module
    #     image: seller-academy-ui-panel:latest
    #     build:
    #         context: .
    #         args:
    #             <<: *buildargs
    #             MODULE: panel
    #     container_name: seller-academy-ui-panel

    nginx:
        image: nginx:latest
        container_name: refactored-seller-academy-ui-rproxy
        ports:
            - 3450:80
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - core
            - blog
            - forum
            - academy
