version: '3.7'

x-buildargs: &buildargs
    API_BASE_URL: ${API_BASE_URL}
    APP_NAME: ${APP_NAME}
    PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
    SELLER_PANEL_LOGIN_URL: ${SELLER_PANEL_LOGIN_URL}
    NEED_AUTH: ${NEED_AUTH}
    ACADEMY_VERSION: ${ACADEMY_VERSION}

x-module: &module
    env_file: .env
    build:
        context: .
        args:
            API_BASE_URL: ${API_BASE_URL}
            APP_NAME: ${APP_NAME}
            PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
            SELLER_PANEL_LOGIN_URL: ${SELLER_PANEL_LOGIN_URL}
            NEED_AUTH: ${NEED_AUTH}
            ACADEMY_VERSION: ${ACADEMY_VERSION}
    restart: unless-stopped
    depends_on:
        - next

services:
    next:
        image: diginext-core-ui-refactored:latest
        env_file: .env
        platform: linux/x86_64
        build:
            context: .
            args:
                <<: *buildargs
        container_name: refactored-diginext-core-ui
        restart: unless-stopped
    


    webserver:
        image: nginx:latest
        container_name: refactored-diginext-ui-rproxy
        ports:
            - 3244:80
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - next
