name: Main Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.TEST_SERVER_HOST }}
        username: ${{ secrets.TEST_SERVER_USERNAME }}
        key: ${{ secrets.TEST_SERVER_KEY }}
        port: ${{ secrets.TEST_SERVER_PORT }}
        command_timeout: 20m
        script: sudo bash -c "cd /home/projects/sellerhub/frontend-sellerhub && git pull origin main && docker-compose build && docker-compose down && docker-compose up -d"
